# PyTorch  

## Tensor

In [2]:
import torch

In [3]:
x=torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 7.5306e-39],
        [8.7245e-39, 6.1531e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [4]:
x=torch.rand(5,3)
x

tensor([[0.2208, 0.7601, 0.6669],
        [0.8047, 0.7985, 0.3774],
        [0.3620, 0.7943, 0.2164],
        [0.3425, 0.6234, 0.8683],
        [0.9174, 0.0396, 0.5050]])

In [5]:
x=torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
x=torch.zeros(5,3).long()
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
x=torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [13]:
x=x.new_ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[ 1.4480, -0.7826,  0.7219],
        [ 0.9393, -0.0549, -0.0789],
        [ 1.8989,  1.0364,  0.5109],
        [-0.8122, -0.7583, -0.3266],
        [-0.1731,  0.5951, -0.4782]])

In [18]:
x.shape

torch.Size([5, 3])

In [20]:
x.size()

torch.Size([5, 3])

## Operations

In [22]:
y=torch.rand(5,3)
y

tensor([[0.3114, 0.6448, 0.4469],
        [0.9463, 0.5817, 0.4637],
        [0.5784, 0.3324, 0.3888],
        [0.3791, 0.9662, 0.4335],
        [0.4680, 0.0426, 0.9858]])

In [23]:
x

tensor([[ 1.4480, -0.7826,  0.7219],
        [ 0.9393, -0.0549, -0.0789],
        [ 1.8989,  1.0364,  0.5109],
        [-0.8122, -0.7583, -0.3266],
        [-0.1731,  0.5951, -0.4782]])

In [24]:
x+y

tensor([[ 1.7595, -0.1378,  1.1688],
        [ 1.8855,  0.5267,  0.3848],
        [ 2.4773,  1.3688,  0.8997],
        [-0.4331,  0.2079,  0.1069],
        [ 0.2949,  0.6377,  0.5076]])

In [25]:
torch.add(x,y)

tensor([[ 1.7595, -0.1378,  1.1688],
        [ 1.8855,  0.5267,  0.3848],
        [ 2.4773,  1.3688,  0.8997],
        [-0.4331,  0.2079,  0.1069],
        [ 0.2949,  0.6377,  0.5076]])

In [26]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[ 1.7595, -0.1378,  1.1688],
        [ 1.8855,  0.5267,  0.3848],
        [ 2.4773,  1.3688,  0.8997],
        [-0.4331,  0.2079,  0.1069],
        [ 0.2949,  0.6377,  0.5076]])

In [28]:
result=x+y
result

tensor([[ 1.7595, -0.1378,  1.1688],
        [ 1.8855,  0.5267,  0.3848],
        [ 2.4773,  1.3688,  0.8997],
        [-0.4331,  0.2079,  0.1069],
        [ 0.2949,  0.6377,  0.5076]])

### in-place

In [29]:
y.add_(x)
y

tensor([[ 1.7595, -0.1378,  1.1688],
        [ 1.8855,  0.5267,  0.3848],
        [ 2.4773,  1.3688,  0.8997],
        [-0.4331,  0.2079,  0.1069],
        [ 0.2949,  0.6377,  0.5076]])

In [31]:
x[:,1:]

tensor([[-0.7826,  0.7219],
        [-0.0549, -0.0789],
        [ 1.0364,  0.5109],
        [-0.7583, -0.3266],
        [ 0.5951, -0.4782]])

### resizing

In [34]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)
z=x.view(2,8)
print(z)
t=x.view(2,-1)
print(t)

tensor([[0.5963, 0.4531, 0.4895, 0.3420],
        [0.2500, 0.1919, 0.2045, 0.7810],
        [0.2526, 0.9666, 0.5129, 0.2281],
        [0.0399, 0.0234, 0.6676, 0.4813]])
tensor([0.5963, 0.4531, 0.4895, 0.3420, 0.2500, 0.1919, 0.2045, 0.7810, 0.2526,
        0.9666, 0.5129, 0.2281, 0.0399, 0.0234, 0.6676, 0.4813])
tensor([[0.5963, 0.4531, 0.4895, 0.3420, 0.2500, 0.1919, 0.2045, 0.7810],
        [0.2526, 0.9666, 0.5129, 0.2281, 0.0399, 0.0234, 0.6676, 0.4813]])
tensor([[0.5963, 0.4531, 0.4895, 0.3420, 0.2500, 0.1919, 0.2045, 0.7810],
        [0.2526, 0.9666, 0.5129, 0.2281, 0.0399, 0.0234, 0.6676, 0.4813]])


### 只有一个元素的tensor，使用.item()方法可以把里面的value变成Python数值。

In [35]:
x=torch.rand(1)
x

tensor([0.5938])

In [37]:
dir(x)
#data
#grad
#grad_fn

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__se

In [38]:
print(x.data)
print(x.grad)

tensor([0.5938])
None


In [41]:
x.item()

0.5937507748603821

In [42]:
z.transpose(1,0)

tensor([[0.5963, 0.2526],
        [0.4531, 0.9666],
        [0.4895, 0.5129],
        [0.3420, 0.2281],
        [0.2500, 0.0399],
        [0.1919, 0.0234],
        [0.2045, 0.6676],
        [0.7810, 0.4813]])

### 更多阅读

各种Tensor operations, 包括transposing, indexing, slicing, mathematical operations, linear algebra, random numbers在 <https://pytorch.org/docs/torch>.

## Numpy与Tensor之间转化

### Tensor->Numpy

In [44]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [48]:
b=a.numpy()
b

array([1., 2., 1., 1., 1.], dtype=float32)

注意：a，b共享内存空间

In [46]:
b[1]=2
b

array([1., 2., 1., 1., 1.], dtype=float32)

In [47]:
a

tensor([1., 2., 1., 1., 1.])

### Numpy->Tensor

In [63]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

注意：a，b共享内存空间

In [64]:
a[1]=2
a

array([1., 2., 1., 1., 1.])

In [65]:
b

tensor([1., 2., 1., 1., 1.], dtype=torch.float64)

In [67]:
a=a+1
a

array([3., 4., 3., 3., 3.])

In [68]:
b

tensor([1., 2., 1., 1., 1.], dtype=torch.float64)

## CUDA Tensors

In [70]:
torch.cuda.is_available()

True

In [72]:
device=torch.device('cuda')
y=torch.ones_like(x,device=device)
y

tensor([1.], device='cuda:0')

In [74]:
x=x.to(device)
z=x+y
print(z)
print(z.to('cpu'))
print(z.to('cpu',torch.double))

tensor([1.5938], device='cuda:0')
tensor([1.5938])
tensor([1.5938], dtype=torch.float64)


gpu中数据不能直接转化为numpy数据 需要先转到cpu中  
numpy数据在cpu上操作

In [84]:
q=torch.rand(5,3,device=device)
q
c=q.to('cpu').data.numpy()
# q.cpu().data.numpy()
print(c)
print(type(c))

[[0.6269689  0.5623227  0.01049137]
 [0.7307416  0.43149674 0.69761956]
 [0.6553753  0.51908356 0.6943256 ]
 [0.01653855 0.5959171  0.47122547]
 [0.09330803 0.39578336 0.5964598 ]]
<class 'numpy.ndarray'>


将模型搬入gpu

In [ ]:
model=model.cuda()

## 用numpy实现两层神经网络

一个全连接ReLU神经网络，一个隐含层，没有bias  
- $h=W_1X$  
- $a=max(0,h)$
- $y_{hat}=W_2a$

完全使用numpy计算前向神经网络，loss和backpropagation  
- forward pass  
- loss  
- backward pass  

In [2]:
import numpy as np
#N: 输入个数
#D_in：维度
#H：hidden layer维度
#D_out：输出维度
N, D_in, H, D_out=64,1000,100,10

#随机创建训练数据
x=np.random.randn(N,D_in)
y=np.random.randn(N,D_out)

w1=np.random.randn(D_in,H)
w2=np.random.randn(H,D_out)

learning_rate=1e-6

for it in range(500):
    #Forward pass
    h=x.dot(w1) #N*H
    h_relu=np.maximum(h,0) #N*H
    y_pred=h_relu.dot(w2) #N*D_out
    
    #compute loss
    loss=np.square(y_pred-y).sum()
    print(it,loss)
    
    #Backward pass
    # compute the gradient
    grad_y_pred=2.0*(y_pred-y)
    grad_w2=h_relu.T.dot(grad_y_pred)
    grad_h_relu=grad_y_pred.dot(w2.T)
    grad_h=grad_h_relu.copy()
    grad_h[h<0]=0
    grad_w1=x.T.dot(grad_h)
    
    #update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2

0 28581267.347675964
1 26157225.289634436
2 26766717.128268205
3 26616693.095043615
4 23539180.65749626
5 17630489.99775575
6 11351313.207464835
7 6555585.465408297
8 3683570.7470515165
9 2153854.9231364327
10 1370473.394580257
11 957659.6883527983
12 725374.0028188875
13 581502.7412870566
14 483442.7035153256
15 411059.0036252707
16 354562.84584334353
17 308760.06014819886
18 270638.6688958766
19 238365.49267967854
20 210864.5071995287
21 187245.84117754304
22 166872.4326093053
23 149191.61494642287
24 133803.6186520156
25 120312.66442224673
26 108451.70334311938
27 97960.84142487257
28 88653.56550178188
29 80377.06012278402
30 72999.83634682346
31 66417.09808202472
32 60518.21201248113
33 55217.508177085096
34 50459.64199242194
35 46174.39200965996
36 42310.563177503354
37 38818.70847183845
38 35656.110934301774
39 32789.55355319227
40 30185.053858554194
41 27818.985805035
42 25666.73429186296
43 23708.602968331306
44 21922.34446411695
45 20289.91824721428
46 18795.78317201486
47 174

367 0.03636566884216462
368 0.03514649983679061
369 0.033968420953920136
370 0.0328299130010825
371 0.03173081247641821
372 0.03066874624370678
373 0.02964131490780721
374 0.02864850473199637
375 0.027688936505678108
376 0.026761679840536085
377 0.025865834289965896
378 0.024999672895027844
379 0.02416288608768344
380 0.023354963242688116
381 0.02257333417520137
382 0.021817860656612596
383 0.02108758972304491
384 0.02038188520142814
385 0.019699915964829742
386 0.019040668629334172
387 0.01840376065062823
388 0.017788922004457815
389 0.017193902702522208
390 0.016618961771948593
391 0.016063577401173874
392 0.01552647685925099
393 0.015007253554904402
394 0.01450554183908189
395 0.014020543530261751
396 0.01355238519953171
397 0.013099445851403484
398 0.012661596821031722
399 0.012238473930224283
400 0.011829578527569998
401 0.011434271822209137
402 0.011052176317810074
403 0.010682961789186629
404 0.010326456659484017
405 0.009981657551630729
406 0.009648321865344447
407 0.0093260429

In [3]:
x

array([[-1.67639582,  1.25217825, -0.60135276, ..., -0.4412069 ,
        -0.35452615,  0.2197139 ],
       [ 0.06625453,  0.54070371,  1.25250183, ...,  0.51630559,
         1.20338577, -1.48871205],
       [-1.54077675,  1.0707647 ,  0.75501128, ...,  0.65498974,
         0.28898787, -1.07734203],
       ...,
       [-0.99134977, -0.56304054,  0.14872042, ..., -0.92661933,
         0.27830645,  0.21977346],
       [ 1.85353027,  0.5738337 , -1.29384605, ..., -1.05398031,
        -0.11650791,  1.19444727],
       [-0.21841011, -0.29410019, -0.71439535, ..., -0.07449753,
         0.30309238, -0.14423705]])

In [4]:
y

array([[-8.60766177e-01, -8.86470958e-01,  1.03308178e+00,
        -1.08563093e-01, -4.14974203e-01, -1.00509168e-01,
         1.36899844e+00,  1.19529636e+00,  2.99192649e-01,
        -3.07891831e-02],
       [-2.11761400e-01, -6.59501742e-01, -4.28059777e-01,
        -2.56061634e-01,  3.56032507e-01, -2.95386217e-02,
        -1.00634839e-01,  6.02322006e-01, -2.77272714e-01,
        -3.08387591e-01],
       [ 1.00287415e+00,  1.06992479e+00, -5.91485599e-01,
         2.21634915e-01, -6.81475964e-01,  7.54946478e-01,
         6.08821634e-01, -5.05601089e-01, -6.27126450e-01,
         1.98147047e-01],
       [-7.75919297e-01, -4.63583744e-01,  4.47321036e-01,
        -1.21222661e+00,  7.30995637e-02,  7.18899556e-02,
        -6.27546367e-01, -4.37633338e-01, -3.69211714e-03,
         9.59152184e-01],
       [ 6.34407486e-01,  9.16470027e-01, -1.93625806e+00,
        -2.97501459e-01, -1.93330659e+00, -6.71659706e-01,
         3.60789974e-01,  1.07678629e+00, -1.77787163e+00,
         5.

In [6]:
h=x.dot(w1) #N*H
h_relu=np.maximum(h,0) #N*H
y_pred=h_relu.dot(w2) #N*D_out
y_pred

array([[-8.60732327e-01, -8.86333218e-01,  1.03355246e+00,
        -1.08926356e-01, -4.15155131e-01, -1.00432177e-01,
         1.36928201e+00,  1.19454918e+00,  2.99698868e-01,
        -3.08508089e-02],
       [-2.11930369e-01, -6.59428538e-01, -4.28378393e-01,
        -2.55839529e-01,  3.56450947e-01, -2.95812279e-02,
        -1.00829638e-01,  6.03042219e-01, -2.77603660e-01,
        -3.08472486e-01],
       [ 1.00316849e+00,  1.06988701e+00, -5.90657735e-01,
         2.20898341e-01, -6.82206074e-01,  7.54974414e-01,
         6.09511854e-01, -5.07919329e-01, -6.25931259e-01,
         1.98108522e-01],
       [-7.76076194e-01, -4.63623721e-01,  4.46677773e-01,
        -1.21182739e+00,  7.33216995e-02,  7.17386556e-02,
        -6.27987859e-01, -4.36599350e-01, -4.56488779e-03,
         9.59085447e-01],
       [ 6.34917023e-01,  9.16614858e-01, -1.93523231e+00,
        -2.98279954e-01, -1.93408696e+00, -6.71563490e-01,
         3.61524598e-01,  1.07491370e+00, -1.77694675e+00,
         5.

In [7]:
y_pred-y

array([[ 3.38499028e-05,  1.37740801e-04,  4.70679752e-04,
        -3.63262791e-04, -1.80927891e-04,  7.69906025e-05,
         2.83570226e-04, -7.47182995e-04,  5.06218875e-04,
        -6.16257952e-05],
       [-1.68968589e-04,  7.32039385e-05, -3.18615871e-04,
         2.22104835e-04,  4.18439616e-04, -4.26062006e-05,
        -1.94799035e-04,  7.20213433e-04, -3.30945851e-04,
        -8.48953631e-05],
       [ 2.94335643e-04, -3.77852726e-05,  8.27864142e-04,
        -7.36574703e-04, -7.30110421e-04,  2.79357712e-05,
         6.90220157e-04, -2.31823996e-03,  1.19519142e-03,
        -3.85254735e-05],
       [-1.56897675e-04, -3.99773334e-05, -6.43262542e-04,
         3.99213187e-04,  2.22135775e-04, -1.51299982e-04,
        -4.41492376e-04,  1.03398790e-03, -8.72770652e-04,
        -6.67377744e-05],
       [ 5.09536411e-04,  1.44831726e-04,  1.02575214e-03,
        -7.78495068e-04, -7.80364692e-04,  9.62160062e-05,
         7.34623702e-04, -1.87258876e-03,  9.24875045e-04,
        -4.