# PyTorch  

## Tensor

In [1]:
import torch

In [2]:
x=torch.empty(5,3)
x

tensor([[-1.2054e+31,  7.0485e-43, -1.2054e+31],
        [ 7.0485e-43, -1.2056e+31,  7.0485e-43],
        [-1.2056e+31,  7.0485e-43, -1.2054e+31],
        [ 7.0485e-43, -1.2054e+31,  7.0485e-43],
        [-1.2063e+31,  7.0485e-43, -1.2063e+31]])

In [3]:
x=torch.rand(5,3)
x

tensor([[0.9036, 0.3033, 0.9130],
        [0.4029, 0.4847, 0.5661],
        [0.5504, 0.8818, 0.6426],
        [0.1243, 0.5718, 0.4542],
        [0.6140, 0.1712, 0.0623]])

In [4]:
x=torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x=torch.zeros(5,3).long()
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x=torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [8]:
x=x.new_ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.3590, -0.2853, -1.1564],
        [-0.7776, -1.2296, -0.6177],
        [-0.8997,  0.9677,  0.0813],
        [-2.2045,  0.0653, -0.0769],
        [ 0.8491, -0.7070,  1.8317]])

In [11]:
x.shape

torch.Size([5, 3])

In [12]:
x.size()

torch.Size([5, 3])

## Operations

In [13]:
y=torch.rand(5,3)
y

tensor([[0.8755, 0.2867, 0.0127],
        [0.3837, 0.0297, 0.4233],
        [0.8964, 0.8032, 0.5710],
        [0.3918, 0.7612, 0.4028],
        [0.3661, 0.9982, 0.1223]])

In [14]:
x

tensor([[ 0.3590, -0.2853, -1.1564],
        [-0.7776, -1.2296, -0.6177],
        [-0.8997,  0.9677,  0.0813],
        [-2.2045,  0.0653, -0.0769],
        [ 0.8491, -0.7070,  1.8317]])

In [15]:
x+y

tensor([[ 1.2345e+00,  1.3376e-03, -1.1437e+00],
        [-3.9388e-01, -1.1999e+00, -1.9441e-01],
        [-3.3356e-03,  1.7709e+00,  6.5228e-01],
        [-1.8127e+00,  8.2651e-01,  3.2597e-01],
        [ 1.2152e+00,  2.9124e-01,  1.9540e+00]])

In [16]:
torch.add(x,y)

tensor([[ 1.2345e+00,  1.3376e-03, -1.1437e+00],
        [-3.9388e-01, -1.1999e+00, -1.9441e-01],
        [-3.3356e-03,  1.7709e+00,  6.5228e-01],
        [-1.8127e+00,  8.2651e-01,  3.2597e-01],
        [ 1.2152e+00,  2.9124e-01,  1.9540e+00]])

In [17]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[ 1.2345e+00,  1.3376e-03, -1.1437e+00],
        [-3.9388e-01, -1.1999e+00, -1.9441e-01],
        [-3.3356e-03,  1.7709e+00,  6.5228e-01],
        [-1.8127e+00,  8.2651e-01,  3.2597e-01],
        [ 1.2152e+00,  2.9124e-01,  1.9540e+00]])

In [18]:
result=x+y
result

tensor([[ 1.2345e+00,  1.3376e-03, -1.1437e+00],
        [-3.9388e-01, -1.1999e+00, -1.9441e-01],
        [-3.3356e-03,  1.7709e+00,  6.5228e-01],
        [-1.8127e+00,  8.2651e-01,  3.2597e-01],
        [ 1.2152e+00,  2.9124e-01,  1.9540e+00]])

### in-place

In [19]:
y.add_(x)
y

tensor([[ 1.2345e+00,  1.3376e-03, -1.1437e+00],
        [-3.9388e-01, -1.1999e+00, -1.9441e-01],
        [-3.3356e-03,  1.7709e+00,  6.5228e-01],
        [-1.8127e+00,  8.2651e-01,  3.2597e-01],
        [ 1.2152e+00,  2.9124e-01,  1.9540e+00]])

In [20]:
x[:,1:]

tensor([[-0.2853, -1.1564],
        [-1.2296, -0.6177],
        [ 0.9677,  0.0813],
        [ 0.0653, -0.0769],
        [-0.7070,  1.8317]])

### resizing

In [21]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)
z=x.view(2,8)
print(z)
t=x.view(2,-1)
print(t)

tensor([[0.5718, 0.5966, 0.7097, 0.0847],
        [0.4020, 0.3354, 0.0650, 0.9667],
        [0.6212, 0.1891, 0.8096, 0.4086],
        [0.1494, 0.6251, 0.6963, 0.5095]])
tensor([0.5718, 0.5966, 0.7097, 0.0847, 0.4020, 0.3354, 0.0650, 0.9667, 0.6212,
        0.1891, 0.8096, 0.4086, 0.1494, 0.6251, 0.6963, 0.5095])
tensor([[0.5718, 0.5966, 0.7097, 0.0847, 0.4020, 0.3354, 0.0650, 0.9667],
        [0.6212, 0.1891, 0.8096, 0.4086, 0.1494, 0.6251, 0.6963, 0.5095]])
tensor([[0.5718, 0.5966, 0.7097, 0.0847, 0.4020, 0.3354, 0.0650, 0.9667],
        [0.6212, 0.1891, 0.8096, 0.4086, 0.1494, 0.6251, 0.6963, 0.5095]])


### 只有一个元素的tensor，使用.item()方法可以把里面的value变成Python数值。

In [22]:
x=torch.rand(1)
x

tensor([0.0838])

In [23]:
dir(x)
#data
#grad
#grad_fn

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__se

In [24]:
print(x.data)
print(x.grad)

tensor([0.0838])
None


In [25]:
x.item()

0.08382612466812134

In [26]:
z.transpose(1,0)

tensor([[0.5718, 0.6212],
        [0.5966, 0.1891],
        [0.7097, 0.8096],
        [0.0847, 0.4086],
        [0.4020, 0.1494],
        [0.3354, 0.6251],
        [0.0650, 0.6963],
        [0.9667, 0.5095]])

### 更多阅读

各种Tensor operations, 包括transposing, indexing, slicing, mathematical operations, linear algebra, random numbers在 <https://pytorch.org/docs/torch>.

## Numpy与Tensor之间转化

### Tensor->Numpy

In [27]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

注意：a，b共享内存空间

In [29]:
b[1]=2
b

array([1., 2., 1., 1., 1.], dtype=float32)

In [30]:
a

tensor([1., 2., 1., 1., 1.])

### Numpy->Tensor

In [31]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

注意：a，b共享内存空间

In [32]:
a[1]=2
a

array([1., 2., 1., 1., 1.])

In [33]:
b

tensor([1., 2., 1., 1., 1.], dtype=torch.float64)

In [34]:
a=a+1
a

array([2., 3., 2., 2., 2.])

In [35]:
b

tensor([1., 2., 1., 1., 1.], dtype=torch.float64)

## CUDA Tensors

In [36]:
torch.cuda.is_available()

True

In [37]:
device=torch.device('cuda')
y=torch.ones_like(x,device=device)
y

tensor([1.], device='cuda:0')

In [38]:
x=x.to(device)
z=x+y
print(z)
print(z.to('cpu'))
print(z.to('cpu',torch.double))

tensor([1.0838], device='cuda:0')
tensor([1.0838])
tensor([1.0838], dtype=torch.float64)


gpu中数据不能直接转化为numpy数据 需要先转到cpu中  
numpy数据在cpu上操作

In [39]:
q=torch.rand(5,3,device=device)
q
c=q.to('cpu').data.numpy()
# q.cpu().data.numpy()
print(c)
print(type(c))

[[0.8187222  0.3047521  0.83184224]
 [0.07137126 0.22800346 0.6427909 ]
 [0.78549975 0.5282124  0.19792424]
 [0.39749813 0.7239286  0.3963733 ]
 [0.47504354 0.9474314  0.90231246]]
<class 'numpy.ndarray'>


将模型搬入gpu

In [40]:
# model=model.cuda()

## 用numpy实现两层神经网络

一个全连接ReLU神经网络，一个隐含层，没有bias  
- $h=W_1X$  
- $a=max(0,h)$
- $y_{hat}=W_2a$

完全使用numpy计算前向神经网络，loss和backpropagation  
- forward pass  
- loss  
- backward pass  

In [41]:
import numpy as np
#N: 输入个数
#D_in：维度
#H：hidden layer维度
#D_out：输出维度
N, D_in, H, D_out=64,1000,100,10

#随机创建训练数据
x=np.random.randn(N,D_in)
y=np.random.randn(N,D_out)

w1=np.random.randn(D_in,H)
w2=np.random.randn(H,D_out)

learning_rate=1e-6

for it in range(500):
    #Forward pass
    h=x.dot(w1) #N*H
    h_relu=np.maximum(h,0) #N*H
    y_pred=h_relu.dot(w2) #N*D_out
    
    #compute loss
    loss=np.square(y_pred-y).sum()
    print(it,loss)
    
    #Backward pass
    # compute the gradient
    grad_y_pred=2.0*(y_pred-y)
    grad_w2=h_relu.T.dot(grad_y_pred)
    grad_h_relu=grad_y_pred.dot(w2.T)
    grad_h=grad_h_relu.copy()
    grad_h[h<0]=0
    grad_w1=x.T.dot(grad_h)
    
    #update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2

0 31011780.308193903
1 24307226.438550405
2 20651908.098391023
3 17229441.09948735
4 13461798.002672646
5 9782998.533830717
6 6720222.742806565
7 4502352.2487392835
8 3030520.9929866856
9 2097783.0376668978
10 1511735.5152860726
11 1137541.6251079612
12 890252.1216122101
13 719468.1999463296
14 595962.066329831
15 502793.21747553616
16 430009.7630278376
17 371628.449918921
18 323776.57284617174
19 283929.4372167246
20 250333.7310007261
21 221785.98938475107
22 197397.98325399292
23 176305.30394824198
24 157981.17805023614
25 141987.40731823808
26 127969.7567071173
27 115630.30975194389
28 104721.78583432816
29 95048.87461920794
30 86443.60036944569
31 78766.7588444666
32 71906.14427383154
33 65759.9144897393
34 60236.91495017113
35 55257.37079853232
36 50761.02683961422
37 46701.905067410786
38 43025.6890443981
39 39682.092308663465
40 36637.75349798913
41 33860.62068246327
42 31324.7203110746
43 29005.479569835392
44 26881.66585553489
45 24935.2360792202
46 23149.375044489032
47 21506

475 5.429192949806838e-06
476 5.181772493674107e-06
477 4.9456871558899394e-06
478 4.72044118721922e-06
479 4.505507944503e-06
480 4.3004216213039806e-06
481 4.1047118270023095e-06
482 3.917982475628184e-06
483 3.739790101019223e-06
484 3.56981514552526e-06
485 3.4075385401659393e-06
486 3.252684727749231e-06
487 3.1048882681851147e-06
488 2.963852437808769e-06
489 2.8292945831341434e-06
490 2.70086576363399e-06
491 2.5782929642234776e-06
492 2.461311966761464e-06
493 2.349660144898662e-06
494 2.243115151380357e-06
495 2.1414391172673683e-06
496 2.044391227580946e-06
497 1.9517617883635122e-06
498 1.8633657587304976e-06
499 1.778993742522711e-06


In [42]:
x

array([[ 1.1491975 ,  0.13601473,  0.21767231, ...,  1.5900089 ,
         0.91361506, -0.03166552],
       [ 0.9331642 , -0.40552381, -0.01576472, ..., -1.43728118,
         0.41644512,  1.42189989],
       [ 0.12040028, -0.38177269, -1.09801045, ...,  1.13893867,
        -0.02475201, -0.26689147],
       ...,
       [ 0.1337317 ,  0.72942931,  0.03232434, ..., -1.43114542,
         0.24964858, -0.3283298 ],
       [-0.19597824,  1.9039508 , -0.23303964, ..., -0.49757546,
         0.2004738 , -0.07481211],
       [ 0.24880801, -0.41503333, -0.08864033, ...,  1.41540346,
        -0.29240701,  1.26825865]])

In [43]:
y

array([[ 4.99597230e-01,  8.84955449e-01,  2.24651693e+00,
        -2.14963545e+00,  2.25819566e+00,  1.14682240e+00,
         2.25718928e-01,  2.01087321e-01, -5.02183955e-01,
        -2.86577934e-01],
       [ 1.33987210e+00, -2.57255238e-02, -1.79021704e-02,
        -5.73064773e-01, -1.32990428e-01, -3.07488864e-01,
         1.79507069e+00,  2.15943530e+00, -7.27867036e-01,
         6.55344447e-01],
       [ 1.05389959e+00, -4.94953748e-01,  8.69702702e-01,
         1.64308118e+00,  3.69826704e-01, -2.85192496e-01,
        -1.70636386e-01,  6.47773551e-01, -4.92443565e-01,
        -1.56817544e-01],
       [-2.95754678e-01, -1.27710560e+00,  3.57513430e-01,
        -8.48356553e-01, -9.45619249e-01, -1.64896627e+00,
         1.09467685e+00, -8.88930043e-01, -1.24896998e-01,
        -1.91641052e-01],
       [ 1.27319410e+00,  1.28447017e-01,  1.78446632e+00,
        -8.04806966e-01,  5.77329000e-01, -4.95780031e-01,
        -6.51032041e-01,  1.72266485e-01,  2.66733282e-01,
        -6.

In [44]:
h=x.dot(w1) #N*H
h_relu=np.maximum(h,0) #N*H
y_pred=h_relu.dot(w2) #N*D_out
y_pred

array([[ 4.99611876e-01,  8.84899520e-01,  2.24651247e+00,
        -2.14963337e+00,  2.25820676e+00,  1.14679991e+00,
         2.25689976e-01,  2.01098032e-01, -5.02211190e-01,
        -2.86579063e-01],
       [ 1.33985493e+00, -2.56923417e-02, -1.78892535e-02,
        -5.73062383e-01, -1.32990061e-01, -3.07470713e-01,
         1.79509550e+00,  2.15943134e+00, -7.27859249e-01,
         6.55343892e-01],
       [ 1.05392264e+00, -4.94948891e-01,  8.69754577e-01,
         1.64307154e+00,  3.69752787e-01, -2.85158800e-01,
        -1.70677452e-01,  6.47821042e-01, -4.92371077e-01,
        -1.56850450e-01],
       [-2.95754305e-01, -1.27710594e+00,  3.57528963e-01,
        -8.48357475e-01, -9.45630400e-01, -1.64895753e+00,
         1.09467507e+00, -8.88916422e-01, -1.24883475e-01,
        -1.91658174e-01],
       [ 1.27311578e+00,  1.28631592e-01,  1.78447453e+00,
        -8.04778946e-01,  5.77344472e-01, -4.95716292e-01,
        -6.50916069e-01,  1.72231604e-01,  2.66761051e-01,
        -6.

In [45]:
y_pred-y

array([[ 1.46463733e-05, -5.59287810e-05, -4.45583289e-06,
         2.08292332e-06,  1.10980096e-05, -2.24895558e-05,
        -2.89525179e-05,  1.07111370e-05, -2.72348026e-05,
        -1.12907279e-06],
       [-1.71688580e-05,  3.31821176e-05,  1.29168991e-05,
         2.39049131e-06,  3.67490633e-07,  1.81513323e-05,
         2.48150833e-05, -3.96001710e-06,  7.78692146e-06,
        -5.55941536e-07],
       [ 2.30492629e-05,  4.85759121e-06,  5.18753054e-05,
        -9.63114635e-06, -7.39171072e-05,  3.36953951e-05,
        -4.10651280e-05,  4.74908133e-05,  7.24879032e-05,
        -3.29056323e-05],
       [ 3.73324675e-07, -3.42111399e-07,  1.55331203e-05,
        -9.22033685e-07, -1.11512619e-05,  8.73934482e-06,
        -1.77333462e-06,  1.36209980e-05,  1.35234798e-05,
        -1.71218042e-05],
       [-7.83165489e-05,  1.84574564e-04,  8.20483912e-06,
         2.80202449e-05,  1.54718436e-05,  6.37386796e-05,
         1.15971846e-04, -3.48810858e-05,  2.77694767e-05,
         3.

## PyTorch: Tensors

这次我们使用PyTorch tensors来创建前向神经网络，计算损失，以及反向传播。

一个PyTorch Tensor很像一个numpy的ndarray。但是它和numpy ndarray最大的区别是，PyTorch Tensor可以在CPU或者GPU上运算。

如果想要在GPU上运算，就需要把Tensor换成cuda类型。

In [46]:
import torch

N, D_in, H, D_out = 64, 1000, 100, 10

# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H)
w2 = torch.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
    # Forward pass
    h = x.mm(w1) # N * H
    h_relu = h.clamp(min=0) # N * H
    y_pred = h_relu.mm(w2) # N * D_out
    
    # compute loss
    loss = (y_pred - y).pow(2).sum().item()
    print(it, loss)
    
    # Backward pass
    # compute the gradient
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h<0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    # update weights of w1 and w2
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 26099416.0
1 21618278.0
2 24632536.0
3 33058408.0
4 43362912.0
5 47103116.0
6 37266088.0
7 19976774.0
8 7956624.0
9 3009262.5
10 1420446.625
11 896576.5625
12 680993.9375
13 560232.625
14 475392.375
15 408854.25
16 354260.4375
17 308567.1875
18 269896.0625
19 236999.109375
20 208826.890625
21 184571.09375
22 163589.28125
23 145381.1875
24 129535.6171875
25 115683.515625
26 103538.15625
27 92856.2578125
28 83434.5
29 75108.5
30 67728.4921875
31 61182.59375
32 55360.36328125
33 50164.44921875
34 45526.94921875
35 41376.76953125
36 37655.23046875
37 34317.88671875
38 31317.7421875
39 28613.322265625
40 26171.830078125
41 23961.98046875
42 21961.1171875
43 20147.75390625
44 18501.13671875
45 17005.2578125
46 15644.7001953125
47 14406.064453125
48 13277.6962890625
49 12247.0859375
50 11305.529296875
51 10443.7080078125
52 9654.130859375
53 8930.5576171875
54 8267.650390625
55 7658.9443359375
56 7099.55517578125
57 6585.3310546875
58 6112.07177734375
59 5676.21142578125
60 5274.5166015625


386 0.0003932099789381027
387 0.00038260716246441007
388 0.0003707160649355501
389 0.0003610510902944952
390 0.00035063427640125155
391 0.0003415769897401333
392 0.00033169641392305493
393 0.00032287556678056717
394 0.00031329772900789976
395 0.00030462106224149466
396 0.0002966710599139333
397 0.0002893194614443928
398 0.0002808962599374354
399 0.0002729627303779125
400 0.0002662409679032862
401 0.00025958914193324745
402 0.00025317849940620363
403 0.0002469143073540181
404 0.00024084121105261147
405 0.0002353050367673859
406 0.00023009725555311888
407 0.00022401257592719048
408 0.00021815262152813375
409 0.00021314871264621615
410 0.00020798161858692765
411 0.00020315077563282102
412 0.00019818823784589767
413 0.00019361382874194533
414 0.00018933843239210546
415 0.00018529339286033064
416 0.00018084252951666713
417 0.00017586085596121848
418 0.0001720756117720157
419 0.0001682666625129059
420 0.0001644685835344717
421 0.00016111139848362654
422 0.0001572658511577174
423 0.0001542779

简单autograd

In [47]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)

y=w*x+b #y=2*1+3

y.backward()

print(w.grad)
print(x.grad)
print(b.grad)

tensor(1.)
tensor(2.)
tensor(1.)


## Pytorch: Tensor 和 autograd

PyTorch的一个重要功能就是autograd，也就是说只要定义了forward pass(前向神经网络)，计算了loss之后，PyTorch可以自动求导计算模型所有参数的梯度。

一个PyTorch的Tensor表示计算图中的一个节点。如果x是一个Tensor并且x.requires_grad=True那么x.grad是另一个储存着x当前梯度(相对于一个scalar，常常是loss)的向量。

### 为了保留loss 不能直接用item()转化为数字，需要在print时转化为数字

### 每一个Tensor的计算都会有个一计算图，有grad时会自动保留grad。  
### 为了防止update weights of w1 and w2后再保留w1与w2的grad，需要加torch.no_grad()

In [48]:
import torch

N, D_in, H, D_out = 64, 1000, 100, 10

# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H,requires_grad=True) #默认requires_grad为False
w2 = torch.randn(H, D_out,requires_grad=True)

learning_rate = 1e-6
for it in range(500):
    # Forward pass
    y_pred=x.mm(w1).clamp(min=0).mm(w2)
    
    # compute loss
    loss = (y_pred - y).pow(2).sum() # computation graph
    print(it,loss.item())
    
    # Backward pass
    loss.backward()
    
    # update weights of w1 and w2
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
    w1.grad.zero_()
    w2.grad.zero_()

0 33894184.0
1 35149312.0
2 37543152.0
3 34352272.0
4 24616082.0
5 13614217.0
6 6558883.0
7 3237196.5
8 1864541.0
9 1267504.375
10 965252.0
11 780731.3125
12 650634.0625
13 551036.375
14 471135.3125
15 405655.40625
16 351348.96875
17 305756.375
18 267214.0625
19 234391.21875
20 206320.203125
21 182221.390625
22 161437.34375
23 143494.046875
24 127854.78125
25 114199.3125
26 102249.5625
27 91745.3203125
28 82487.8515625
29 74304.4375
30 67054.1015625
31 60617.42578125
32 54893.18359375
33 49784.375
34 45218.1796875
35 41133.5546875
36 37475.23828125
37 34191.4140625
38 31238.15625
39 28574.359375
40 26168.6328125
41 23991.66015625
42 22020.35546875
43 20230.947265625
44 18605.330078125
45 17126.53515625
46 15780.06640625
47 14552.0263671875
48 13431.3046875
49 12406.330078125
50 11468.7216796875
51 10610.15234375
52 9823.9736328125
53 9102.66796875
54 8440.2919921875
55 7831.60546875
56 7271.228515625
57 6755.0390625
58 6279.32666015625
59 5841.3525390625
60 5436.97412109375
61 5063.062

405 0.00043288434972055256
406 0.00042281870264559984
407 0.00041164521826431155
408 0.00040168443229049444
409 0.000392055488191545
410 0.00038165977457538247
411 0.00037280094693414867
412 0.00036330876173451543
413 0.00035473715979605913
414 0.00034646873245947063
415 0.00033818744122982025
416 0.0003300132229924202
417 0.00032193755032494664
418 0.00031447529909200966
419 0.00030699814669787884
420 0.0002997111587319523
421 0.0002935055526904762
422 0.0002868099254556
423 0.0002799391222652048
424 0.0002742156502790749
425 0.0002676461008377373
426 0.0002615372941363603
427 0.00025552415172569454
428 0.0002506035380065441
429 0.00024494854733347893
430 0.00023923498520161957
431 0.00023447842977475375
432 0.00022993929451331496
433 0.00022455892758443952
434 0.00022004343918524683
435 0.0002159115538233891
436 0.00021122052567079663
437 0.00020684878109022975
438 0.00020301173208281398
439 0.00019887162488885224
440 0.0001952542515937239
441 0.00019155578047502786
442 0.00018804745

### grad若不清零，每次循环会叠加

In [49]:
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

for i in range(3):
    # Forward pass
    y_pred=x.mm(w1).clamp(min=0).mm(w2)

    # compute loss
    loss = (y_pred - y).pow(2).sum() # computation graph

    # Backward pass
    loss.backward()

    print(w1.grad)

tensor([[ 13195.0117, -11332.4316,   -479.1739,  ...,  -1628.8594,
          -3056.1038,  -5777.8047],
        [-12230.4658,   4136.2026,  20811.2949,  ...,   5928.8540,
          -3736.9021,   7428.4785],
        [  8691.5430,   1901.9600, -26675.4531,  ...,   1254.7081,
           -285.5322, -13352.4961],
        ...,
        [  4239.7695,  -7074.8945,  14442.7236,  ...,  -5164.7803,
           7436.9365,   7700.3496],
        [ -7609.3896,  -4255.3442,  15360.3193,  ...,  -3717.5801,
          -3962.4009,   8552.8750],
        [   215.1607,   2757.1765,  -8619.7246,  ...,   4465.5635,
           4507.0464,   1371.2388]])
tensor([[ 26390.0234, -22664.8633,   -958.3477,  ...,  -3257.7188,
          -6112.2075, -11555.6094],
        [-24460.9316,   8272.4053,  41622.5898,  ...,  11857.7080,
          -7473.8042,  14856.9570],
        [ 17383.0859,   3803.9199, -53350.9062,  ...,   2509.4163,
           -571.0645, -26704.9922],
        ...,
        [  8479.5391, -14149.7891,  28885.4473

### 为了防止每次循环会叠加gradient 需要增加grad.zero_()

In [50]:
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

for i in range(3):
    # Forward pass
    y_pred=x.mm(w1).clamp(min=0).mm(w2)

    # compute loss
    loss = (y_pred - y).pow(2).sum() # computation graph

    # Backward pass
    loss.backward()
    
    print(w1.grad)
    w1.grad.zero_()
    w2.grad.zero_()

tensor([[ -1075.7725,  -9229.5713,  14557.2324,  ...,  -4350.0791,
           9353.5205,  -5601.0190],
        [  2717.9910,   4487.3223,  -7944.7583,  ...,  -2947.6143,
           5890.9961,    376.9238],
        [  4361.6953,  10723.0127,  -6332.5312,  ...,  -8242.5820,
           2067.6514, -19373.7246],
        ...,
        [   554.8401,   4465.1763,   8921.4443,  ...,  -7663.1509,
          -1266.4709,  -6876.8799],
        [  6482.3882,  18223.7930,   9274.6729,  ...,  -4407.4194,
          -5165.7725,   1781.5713],
        [ -1054.9880,   5283.6201,  -3227.4844,  ...,    663.1949,
          -3645.8528,  -1820.8595]])
tensor([[ -1075.7725,  -9229.5713,  14557.2324,  ...,  -4350.0791,
           9353.5205,  -5601.0190],
        [  2717.9910,   4487.3223,  -7944.7583,  ...,  -2947.6143,
           5890.9961,    376.9238],
        [  4361.6953,  10723.0127,  -6332.5312,  ...,  -8242.5820,
           2067.6514, -19373.7246],
        ...,
        [   554.8401,   4465.1763,   8921.4443

## PyTorch: nn

In [51]:
import torch

device=torch.device('cuda')

N, D_in, H, D_out = 64, 1000, 100, 10

# 随机创建一些训练数据
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

model=torch.nn.Sequential(
    torch.nn.Linear(D_in,H), #w_1*x+b_1
    torch.nn.ReLU(),
    torch.nn.Linear(H,D_out),
)

torch.nn.init.normal_(model[0].weight)
torch.nn.init.normal_(model[2].weight)

loss_fn=torch.nn.MSELoss(reduction='sum')

model=model.to(device)

learning_rate = 1e-6

for it in range(500):
    # Forward pass
    # y_pred=model(x)
    y_pred=model.forward(x)
    
    # compute loss
    loss = loss_fn(y_pred,y) # computation graph
    print(it,loss.item())
    
    # Backward pass
    loss.backward()
    
    # update weights of w1 and w2
    with torch.no_grad():
        for param in model.parameters():
            param-=learning_rate*param.grad
    
    model.zero_grad()

0 32390268.0
1 26438384.0
2 22052728.0
3 17198032.0
4 12246794.0
5 8094198.5
6 5180732.5
7 3355230.0
8 2267886.5
9 1619306.0
10 1219067.25
11 958093.0625
12 777314.25
13 644876.875
14 543491.625
15 463192.46875
16 398090.5625
17 344376.0625
18 299543.9375
19 261694.03125
20 229454.609375
21 201844.0
22 178088.125
23 157570.046875
24 139759.75
25 124255.28125
26 110712.59375
27 98836.3125
28 88406.140625
29 79221.5859375
30 71123.40625
31 63968.62109375
32 57621.7265625
33 51981.35546875
34 46957.93359375
35 42480.05078125
36 38485.3203125
37 34909.34765625
38 31702.359375
39 28820.447265625
40 26227.69921875
41 23891.751953125
42 21782.40234375
43 19877.37890625
44 18158.962890625
45 16605.47265625
46 15197.3984375
47 13919.537109375
48 12758.61328125
49 11703.587890625
50 10743.107421875
51 9868.1220703125
52 9070.630859375
53 8342.833984375
54 7678.32568359375
55 7071.23681640625
56 6517.72119140625
57 6012.07861328125
58 5548.9619140625
59 5124.5458984375
60 4735.87548828125
61 4379

480 4.69042788608931e-05
481 4.640804399969056e-05
482 4.59353432233911e-05
483 4.511142469709739e-05
484 4.445622835191898e-05
485 4.386837827041745e-05
486 4.339003498898819e-05
487 4.279968561604619e-05
488 4.232202627463266e-05
489 4.180742325843312e-05
490 4.116682248422876e-05
491 4.067187546752393e-05
492 4.0103888750309125e-05
493 3.956742148147896e-05
494 3.92068614019081e-05
495 3.8603258872171864e-05
496 3.803682193392888e-05
497 3.762648339034058e-05
498 3.725787973962724e-05
499 3.670657315524295e-05


In [52]:
print(model)
print(model[0])
print(model[0].weight)
print(model[0].bias)

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)
Linear(in_features=1000, out_features=100, bias=True)
Parameter containing:
tensor([[-0.1327,  0.3828,  0.1507,  ...,  0.0662,  0.4143, -0.7979],
        [ 0.5639,  0.8993,  0.7533,  ..., -3.0003, -0.6227, -0.4391],
        [-0.5603, -1.6059,  0.4612,  ..., -0.5236,  1.2089,  0.7799],
        ...,
        [ 0.7382, -0.3109, -0.3797,  ..., -0.3973,  0.5690, -0.6400],
        [-0.4813, -0.2438, -0.6971,  ...,  1.3893, -2.5432,  1.4480],
        [-0.7446,  1.5908, -1.1949,  ...,  1.4448,  0.2170,  0.3543]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0394, -0.1750, -0.0908, -0.0664, -0.1731, -0.0495, -0.1811, -0.0703,
        -0.0840, -0.1148, -0.0841, -0.0214, -0.0712, -0.0956, -0.1142, -0.1023,
        -0.0600, -0.1015, -0.0711, -0.0221, -0.0897, -0.0437, -0.0869, -0.1636,
        -0.1212, -0.0762, -0.0882, -

## PyTorch: optim

这次我们使用PyTorch中nn这个库来构建网络。 用PyTorch autograd来构建计算图和计算gradients， 然后PyTorch会帮我们自动计算gradient。

In [53]:
import torch

device=torch.device('cuda')

N, D_in, H, D_out = 64, 1000, 100, 10

# 随机创建一些训练数据
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

model=torch.nn.Sequential(
    torch.nn.Linear(D_in,H), #w_1*x+b_1
    torch.nn.ReLU(),
    torch.nn.Linear(H,D_out),
)

torch.nn.init.normal_(model[0].weight)
torch.nn.init.normal_(model[2].weight)

loss_fn=torch.nn.MSELoss(reduction='sum')

# learning_rate = 1e-4
# optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate) #Adam learning rate一般设为1e-3 to 1e-4

learning_rate = 1e-6
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

model=model.to(device)

for it in range(500):
    # Forward pass
    y_pred=model(x) # model.forward(x)
    
    # compute loss
    loss = loss_fn(y_pred,y) # computation graph
    print(it,loss.item())
    
    # Backward pass
    loss.backward()
    
    #update model parameters
    optimizer.step()
    
    optimizer.zero_grad()

0 24993944.0
1 18684742.0
2 15968095.0
3 14328784.0
4 12823796.0
5 10966267.0
6 8928836.0
7 6863536.0
8 5089791.0
9 3665451.5
10 2626848.25
11 1887077.75
12 1379961.625
13 1030324.625
14 789810.5
15 620952.875
16 500448.75
17 412237.40625
18 346066.375
19 295068.625
20 254876.0625
21 222472.5625
22 195843.40625
23 173597.625
24 154743.9375
25 138642.6875
26 124748.90625
27 112635.875
28 102000.0625
29 92610.640625
30 84278.046875
31 76865.203125
32 70237.203125
33 64295.3671875
34 58958.1953125
35 54150.3359375
36 49812.51953125
37 45885.6640625
38 42324.07421875
39 39085.203125
40 36136.59375
41 33448.890625
42 30993.205078125
43 28746.4765625
44 26687.666015625
45 24801.69921875
46 23068.23046875
47 21474.0625
48 20006.369140625
49 18653.322265625
50 17405.09765625
51 16252.4736328125
52 15187.2490234375
53 14201.0478515625
54 13287.5859375
55 12440.7138671875
56 11654.9267578125
57 10925.314453125
58 10247.30078125
59 9616.861328125
60 9030.1015625
61 8483.3740234375
62 7973.9482421

421 0.0027716823387891054
422 0.0026802311185747385
423 0.0025956016033887863
424 0.0025145900435745716
425 0.0024337973445653915
426 0.002359421458095312
427 0.002287616953253746
428 0.0022183312103152275
429 0.0021481134463101625
430 0.002081375103443861
431 0.0020195699762552977
432 0.001959262415766716
433 0.0018970903474837542
434 0.0018391234334558249
435 0.001783565036021173
436 0.0017304979264736176
437 0.0016782945021986961
438 0.0016299571143463254
439 0.0015797503292560577
440 0.0015355353243649006
441 0.0014888952719047666
442 0.0014446766581386328
443 0.0014031343162059784
444 0.0013627051375806332
445 0.0013232422061264515
446 0.001288664760068059
447 0.0012509971857070923
448 0.0012141524348407984
449 0.0011804007226601243
450 0.0011487358715385199
451 0.001116846688091755
452 0.0010861651971936226
453 0.0010567012941464782
454 0.0010281626600772142
455 0.0009990361286327243
456 0.000971611647401005
457 0.0009460817091166973
458 0.0009205957758240402
459 0.00089646317064

## PyTorch: 自定义nn Modules

我们可以定义一个模型，这个模型继承自nn.Module类。如果需要定义一个比Sequential模型更加复杂的模型，就需要定义nn.Module模型

In [54]:
import torch

device=torch.device('cuda')

N, D_in, H, D_out = 64, 1000, 100, 10

# 随机创建一些训练数据
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        
        #define the model architecture
        self.linear1=torch.nn.Linear(D_in,H)
        self.linear2=torch.nn.Linear(H,D_out)
        
    def forward(self, x):
        y_pred=self.linear2(self.linear1(x).clamp(min=0))
        return y_pred

model=TwoLayerNet(D_in, H, D_out)


loss_fn=torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-4
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

model=model.to(device)

for it in range(500):
    # Forward pass
    y_pred=model(x)
    
    # compute loss
    loss = loss_fn(y_pred,y) # computation graph
    print(it,loss.item())
    
    # Backward pass
    loss.backward()
    
    #update model parameters
    optimizer.step()
    
    optimizer.zero_grad()

0 657.5736083984375
1 640.6243896484375
2 624.159912109375
3 608.1956787109375
4 592.596435546875
5 577.42529296875
6 562.7628173828125
7 548.5498657226562
8 534.6564331054688
9 521.212158203125
10 508.1807861328125
11 495.56048583984375
12 483.27313232421875
13 471.4013977050781
14 459.9036865234375
15 448.727294921875
16 437.87237548828125
17 427.3962707519531
18 417.3053283691406
19 407.4874572753906
20 397.92730712890625
21 388.61334228515625
22 379.49676513671875
23 370.619384765625
24 361.9610595703125
25 353.47052001953125
26 345.177978515625
27 337.09051513671875
28 329.21649169921875
29 321.5397644042969
30 314.10028076171875
31 306.87823486328125
32 299.83953857421875
33 292.95611572265625
34 286.2190246582031
35 279.6158447265625
36 273.1297912597656
37 266.7663269042969
38 260.5335693359375
39 254.42474365234375
40 248.45640563964844
41 242.62315368652344
42 236.8947296142578
43 231.27761840820312
44 225.791015625
45 220.45855712890625
46 215.23733520507812
47 210.114501953

371 1.8176926460000686e-05
372 1.7037260477081873e-05
373 1.5969148080330342e-05
374 1.4968537470849697e-05
375 1.403032092639478e-05
376 1.315134340984514e-05
377 1.23294103104854e-05
378 1.1557450307009276e-05
379 1.0834159184014425e-05
380 1.0156778444070369e-05
381 9.522426807961892e-06
382 8.927263479563408e-06
383 8.370499017473776e-06
384 7.848076165828388e-06
385 7.358118637057487e-06
386 6.898224910401041e-06
387 6.468047558882972e-06
388 6.065034540370107e-06
389 5.6866570048441645e-06
390 5.332389264367521e-06
391 4.999800239602337e-06
392 4.687792170443572e-06
393 4.39592531620292e-06
394 4.122004611417651e-06
395 3.865094640786992e-06
396 3.624121973189176e-06
397 3.3985199934249977e-06
398 3.1867343750491273e-06
399 2.988263531733537e-06
400 2.802193648676621e-06
401 2.6271875412930967e-06
402 2.4633779958094237e-06
403 2.309921228516032e-06
404 2.165656042052433e-06
405 2.0308634702814743e-06
406 1.9039960079680895e-06
407 1.7851773463917198e-06
408 1.6735738199713523e-0